#!/usr/bin/python

import os
import subprocess

home_dir = os.path.expanduser("~")
ANKIDIR = os.path.join(home_dir, '.local/share/Anki2')

print('Pulling latest changes...')
subprocess.run(['git', 'pull'], cwd=ANKIDIR)
print('Adding latest changes...')
subprocess.run(['git', 'add', '.'], cwd=ANKIDIR)

commit_msg = subprocess.check_output(['curl', '-s', 'http://whatthecommit.com/index.txt']).decode('utf-8').strip()
print('Commiting latest changes...')
subprocess.run(['git', 'commit', '-m', commit_msg], cwd=ANKIDIR)

print('Pushing latest changes...')
subprocess.run(['git', 'push'], cwd=ANKIDIR)
