return {
  "m4xshen/hardtime.nvim",
  -- event = "User AstroFile",
  opts = {
    disabled_filetypes = {
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui*",
      "Diffview*",
      "Dressing*",
      "help",
      "httpResult",
      "lazy",
      "Neogit*",
      "mason",
      "neotest%-summary",
      "minifiles",
      "neo%-tree*",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
      "oil",
      "undotree",
      "Trouble",
      "trouble",
      "lspinfo",
    },
  },
}
